### PR TITLE
Added CONTRIBUTION.md 

### PR DESCRIPTION
**Pull request by mohammadshaad**
Asslamulaikum
I have added CONTRIBUTION.md file. I have explained each and every step properly. Inshallah, it will definitely helping contributors while contributing in this repository. 
Jazakallah

### CODE REVIEW

**Comment by Fliw** [comment]
Waalaikumsalam, thankyou for submitting pull request to my repository.
I've the contribution markdown, before i merged it, i want to ask you a little question, is this for hacktoberfest event? or just for making a tribute for open source?

**Comment by mohammadshaad** [comment]
It is just a tribute for open source contribution but as hacktoberfest is going on I was searching for repos under hacktoberfest tag and I found this repo so I made PR. :)

**Review by Fliw — APPROVED** [review]
> It is just a tribute for open source contribution but as hacktoberfest is going on I was searching for repos under hacktoberfest tag and I found this repo so I made PR. :)  

okay, i'm going to merge it with label hacktoberfest accepted, thankyou!

**Comment by mohammadshaad** [comment]
Thank you so much

**Pull request merged**
